### ISSUE TITLE
replace path separators into Path.DirectorySeparatorChar

### ISSUE THREAD

**Issue by ghost** [wiiNinja/NUS.downloader.command.line#1]
unix path separator is slash / instead of backslash \
use Path.DirectorySeparatorChar to do it portable (will work fine with Mono)
please fix this issue (already fixed on upstream nus downloader), this command line tool is really useful for unix users.

**Comment by wiiNinja** [comment]
Picked up the latest version of source code 1.9 from WB3000 in versions after 0.3. So this should no longer be an issue, although I did not test it in a Linux environment.
