### ISSUE TITLE
Net framework 3.5 request

### ISSUE THREAD

**Issue by xflak** [wiiNinja/NUS.downloader.command.line#2]
Is it possible to compile a version that runs off net framework 3.5 instead of 4.8?

You offered to do this for me awhile ago and I only now realized when I need it that I never took you up on it

More info here
https://gbatemp.net/threads/about-nusd-is-this-normal.589974/post-9684789

**Comment by wiiNinja** [comment]
Implemented. See branch dotnet3.5

**Comment by xflak** [comment]
Amazing, thank you!
